# sum, max, min, mean등의 aggregation

In [1]:
import torch

In [8]:
ts_01 = torch.arange(10).view(2, 5)
print(ts_01.max())
print(ts_01)

tensor(9)
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [10]:
print('total sum:', ts_01.sum())
print('sum along dim=0:', ts_01.sum(dim=0)) #dim0 방향으로 sum (아래 방향으로 합계) (열끼리 합)
print('sum along dim=1:', ts_01.sum(dim=1)) #dim1 방향으로 sum (가로(행) 방향으로 합계)

total sum: tensor(45)
sum along dim=0: tensor([ 5,  7,  9, 11, 13])
sum along dim=1: tensor([10, 35])


In [11]:
print('max overall:', ts_01.max())
print('max along dim=0:', ts_01.max(dim=0))# max값과 max가 위치한 index값을 함께 반환. 
print('max along dim=1:', ts_01.max(dim=1))

max overall: tensor(9)
max along dim=0: torch.return_types.max(
values=tensor([5, 6, 7, 8, 9]),
indices=tensor([1, 1, 1, 1, 1]))
max along dim=1: torch.return_types.max(
values=tensor([4, 9]),
indices=tensor([4, 4]))


In [12]:
print('overall mean:', ts_01.mean(dtype=torch.float64))
print('mean along dim=0:', ts_01.mean(dim=0, dtype=torch.float64))
print('mean along dim=1:', ts_01.mean(dim=1, dtype=torch.float64))

overall mean: tensor(4.5000, dtype=torch.float64)
mean along dim=0: tensor([2.5000, 3.5000, 4.5000, 5.5000, 6.5000], dtype=torch.float64)
mean along dim=1: tensor([2., 7.], dtype=torch.float64)


In [13]:
print('min overall:', ts_01.min())
print('min along dim=0:', ts_01.min(dim=0))# min값과 min이 위치한 index값을 함께 반환. 
print('min along dim=1:', ts_01.min(dim=1))

min overall: tensor(0)
min along dim=0: torch.return_types.min(
values=tensor([0, 1, 2, 3, 4]),
indices=tensor([0, 0, 0, 0, 0]))
min along dim=1: torch.return_types.min(
values=tensor([0, 5]),
indices=tensor([0, 0]))


In [14]:
# 3차원일때

ts_02 = torch.arange(24).reshape(2, 3, 4)
print(ts_02)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [15]:
print('total sum:', ts_02.sum())
print('sum along dim=0:\n', ts_02.sum(dim=0))
print('sum along dim=1:\n', ts_02.sum(dim=1))
print('sum along dim=2:\n', ts_02.sum(dim=2))
print('sum along dim=-1:\n', ts_02.sum(dim=-1))

total sum: tensor(276)
sum along dim=0:
 tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
sum along dim=1:
 tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
sum along dim=2:
 tensor([[ 6, 22, 38],
        [54, 70, 86]])
sum along dim=-1:
 tensor([[ 6, 22, 38],
        [54, 70, 86]])


dim= -1는 dim 끝과 같다

In [16]:
# dim 2개 일때 (잘 안씀)
print(ts_02)
print('sum along dim=(1, 2):\n', ts_02.sum(dim=(1, 2)))
print('sum along dim=(2, 1):\n', ts_02.sum(dim=(2, 1)))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
sum along dim=(1, 2):
 tensor([ 66, 210])
sum along dim=(2, 1):
 tensor([ 66, 210])
