# arrange

In [1]:
import torch

In [2]:
seq_ts = torch.arange(10)
print(seq_ts)
print(seq_ts.dtype, seq_ts.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64 torch.Size([10])


# zeros

In [6]:
torch.zeros(size=(3, 2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [13]:
torch.zeros(3, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
torch.zeros(size=(3, 2), dtype=torch.int32).dtype

torch.int32

# ones

In [16]:
one_ts = torch.ones(size=(3, 2), dtype=torch.int16)
print(one_ts)
print(one_ts.dtype, one_ts.shape)

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)
torch.int16 torch.Size([3, 2])
