# indexing

In [1]:
import torch

ts_01 = torch.arange(0, 10).view(2, 5)
print(ts_01)

# 지정 인덱싱 적용
print('ts_01[0, 0]:', ts_01[0, 0], 'ts_01[0, 1]:', ts_01[0, 1])
print('ts_01[1, 0]:', ts_01[1, 0], 'ts_01[1, 2]:', ts_01[1, 2])
print(ts_01[0, 0].shape, ts_01[0, 0].ndim, ts_01[0, :].shape, ts_01[0, :].ndim)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
ts_01[0, 0]: tensor(0) ts_01[0, 1]: tensor(1)
ts_01[1, 0]: tensor(5) ts_01[1, 2]: tensor(7)
torch.Size([]) 0 torch.Size([5]) 1


In [3]:
print(ts_01)
print('ts_01[0, :]은', ts_01[0, :], 'ts_01[:, 0]은', ts_01[:, 0]) #1차원
print('ts_01[0, 0:3]은', ts_01[0, 0:3], 'ts_01[1, 1:4]은', ts_01[1, 1:4]) #1차원
print('ts_01[:, :]\n', ts_01[:, :])

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
ts_01[0, :]은 tensor([0, 1, 2, 3, 4]) ts_01[:, 0]은 tensor([0, 5])
ts_01[0, 0:3]은 tensor([0, 1, 2]) ts_01[1, 1:4]은 tensor([6, 7, 8])
ts_01[:, :]
 tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [7]:
torch.manual_seed(2025)

random_indexes = torch.randint(0, 5, size=(4,)) #1차원 4개
print('random_indexes:', random_indexes)

random_indexes: tensor([1, 4, 4, 1])


In [8]:
torch.manual_seed(2025)

random_indexes = torch.randint(0, 5, size=(4,)) #1차원 4개
print('random_indexes:', random_indexes)

ts_01 = torch.rand(size=(10, 5))
print('ts_01:\n', ts_01)

ts_01_1 = ts_01[random_indexes] # fancy indexing 적용
print('ts_01_1:\n', ts_01_1)

random_indexes: tensor([1, 4, 4, 1])
ts_01:
 tensor([[0.7470, 0.0215, 0.0654, 0.7855, 0.3883],
        [0.6340, 0.9447, 0.4773, 0.2861, 0.3887],
        [0.1099, 0.3606, 0.8450, 0.8059, 0.0520],
        [0.3438, 0.5326, 0.5318, 0.0709, 0.8716],
        [0.6798, 0.2956, 0.9812, 0.9813, 0.8118],
        [0.0463, 0.9592, 0.5132, 0.3941, 0.6953],
        [0.7350, 0.0309, 0.8294, 0.3368, 0.6413],
        [0.6471, 0.5964, 0.9792, 0.8084, 0.9328],
        [0.8772, 0.1945, 0.5616, 0.6019, 0.5040],
        [0.0028, 0.2127, 0.0655, 0.0905, 0.2134]])
ts_01_1:
 tensor([[0.6340, 0.9447, 0.4773, 0.2861, 0.3887],
        [0.6798, 0.2956, 0.9812, 0.9813, 0.8118],
        [0.6798, 0.2956, 0.9812, 0.9813, 0.8118],
        [0.6340, 0.9447, 0.4773, 0.2861, 0.3887]])


In [10]:
ts_01 = torch.arange(1, 11).view(2, 5)
print(ts_01)

mask = ts_01 > 4
print(mask)
print(ts_01[mask]) # pytorch tensor의 boolean indexing은 1차원 tensor를 반환.

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([[False, False, False, False,  True],
        [ True,  True,  True,  True,  True]])
tensor([ 5,  6,  7,  8,  9, 10])


In [11]:
# where는 원본 배열 차원을 보존
torch.where(ts_01 > 4, input=ts_01, other=torch.tensor(999))

tensor([[999, 999, 999, 999,   5],
        [  6,   7,   8,   9,  10]])