# random

rand(): 0 ~ 1 사이의 균일 분포 랜덤값 생성

ranint(): random 정수값을 생성

randn(): 정규 분포 랜덤값 생성

In [3]:
import torch

torch.manual_seed(2025)  # random 수행 시 마다 동일 값 생성을 위한 seed값 할당. 

In [4]:
ts_01 = torch.rand(size=(3, 4)) # 0 ~ 1 사이의 float32 random값. 1제외
print('ts_01:\n', ts_01, ts_01.dtype)
print(ts_01.min(), ts_01.max())

ts_01:
 tensor([[0.6850, 0.9355, 0.2900, 0.3991],
        [0.7470, 0.0215, 0.0654, 0.7855],
        [0.3883, 0.6340, 0.9447, 0.4773]]) torch.float32
tensor(0.0215) tensor(0.9447)


In [8]:
ts_01 = torch.randint(low=0, high=100, size=(3, 4)) # 0 ~ 99까지의 random value
print('ts_01:\n', ts_01, ts_01.dtype)
print(ts_01.min(), ts_01.max())

ts_01:
 tensor([[37, 63, 21,  7],
        [14, 93, 46, 76],
        [52, 26, 42, 55]]) torch.int64
tensor(7) tensor(93)


In [9]:
ts_01 = torch.randn(size=(3, 4)) # 평균이 0 이고, 분산이 1인 정규 분포 random value. 
print('ts_01:\n', ts_01, ts_01.dtype)
print(ts_01.min(), ts_01.max(), ts_01.mean(), ts_01.var())

ts_01:
 tensor([[ 1.5240,  0.3135, -0.1225, -0.7499],
        [ 2.1797, -1.2386,  0.8984,  0.2925],
        [ 0.3088, -0.1869,  2.3893,  0.4012]]) torch.float32
tensor(-1.2386) tensor(2.3893) tensor(0.5008) tensor(1.1970)
