# reshape(), view()

둘 다 tensor 형태 변환 (view()는 contiguous memory 구조에서만 동작)

contiguous memory: 연속 메모리

In [9]:
import torch 

ts_01 = torch.arange(10)
print('ts_01:\n', ts_01)

ts_02 = ts_01.reshape((2, 5))
print('ts_02:\n',ts_02)

ts_03 = ts_01.reshape(5, 2)
print('ts_03:\n',ts_03)

ts_01:
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ts_02:
 tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
ts_03:
 tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [7]:
# 3차원 변경

ts_01 = torch.arange(12)
print('ts_01:\n', ts_01)

ts_04 = ts_01.reshape(2, 3, 2) 
print('ts_04:\n',ts_04)

ts_01:
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
ts_04:
 tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])


In [11]:
ts_01 = torch.arange(10)

ts_02 = ts_01.view((2, 5))
print('ts_02:\n', ts_02, ts_02.shape)

ts_02:
 tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]) torch.Size([2, 5])


In [12]:
torch.manual_seed(2025) 

ts_01 = torch.rand(size=(16, 3, 32, 32)) # 4차원
ts_02 = ts_01.view(16, -1) # 차원
print(ts_02.shape)

torch.Size([16, 3072])


위에 [16, 3, 32, 32] 를 2차원으로 바꾸고 싶다면 [16, -1]를 넣어주면 된다.
[16, 3 * 32 * 32]

In [13]:
#기본적으로 tensor는 contiguous memory 구조로 생성됨. 
ts_01 = torch.arange(10)
ts_02 = ts_01.view(2, -1)
ts_03 = ts_01.reshape(2, -1)

print(ts_01.is_contiguous(), ts_02.is_contiguous(), ts_03.is_contiguous())
# True, True, True

True True True


기본적으로 tensor는 contiguous memory 구조이기때문에 view()를 권장함

In [14]:
ts_02

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])