# squeeze(), unsqueeze()

squeeze: 쥐어짜다
squeeze(): 1로 되어 있는 차원값을 없앤 tensor 반환

1인것만 줄여줌 1이 아니면 그대로 반환

In [1]:
import torch
torch.manual_seed(2025)

ts_01 = torch.rand(size=(1, 4, 5))
print(ts_01)

ts_01_1 = ts_01.squeeze() #차원값을 줄여줌 (1인것을 없애줌) (1, 4, 5) -> (4, 5)
print('ts_01 shape:', ts_01.shape, 'ts_01 squeezed shape:', ts_01_1.shape)
print(ts_01_1)

tensor([[[0.6850, 0.9355, 0.2900, 0.3991, 0.7470],
         [0.0215, 0.0654, 0.7855, 0.3883, 0.6340],
         [0.9447, 0.4773, 0.2861, 0.3887, 0.1099],
         [0.3606, 0.8450, 0.8059, 0.0520, 0.3438]]])
ts_01 shape: torch.Size([1, 4, 5]) ts_01 squeezed shape: torch.Size([4, 5])
tensor([[0.6850, 0.9355, 0.2900, 0.3991, 0.7470],
        [0.0215, 0.0654, 0.7855, 0.3883, 0.6340],
        [0.9447, 0.4773, 0.2861, 0.3887, 0.1099],
        [0.3606, 0.8450, 0.8059, 0.0520, 0.3438]])


In [3]:
# squeeze(dim=0)과 같이 dim 인자 적용
ts_01 = torch.rand(size=(1, 4, 1))
ts_01_1 = ts_01.squeeze(dim=0)
ts_01_2 = ts_01.squeeze(dim=-1)
ts_01_3 = ts_01.squeeze(dim=(0, -1)) #2개가 날라감

print(ts_01.shape, ts_01_1.shape, ts_01_2.shape, ts_01_3.shape)

torch.Size([1, 4, 1]) torch.Size([4, 1]) torch.Size([1, 4]) torch.Size([4])


In [4]:
# 보통은 batch가 포함된 4차원 이미지 tensor에서 batch가 1일 경우 3차원 단일 이미지 tensor로 변환하는데 주로 사용 
ts_01 = torch.rand(size=(1, 3, 64, 64))
ts_01_1 = ts_01.squeeze(dim=0)
print('ts_01 shape:', ts_01.shape, 'ts_01 squeezed shape:', ts_01_1.shape)

ts_01 shape: torch.Size([1, 3, 64, 64]) ts_01 squeezed shape: torch.Size([3, 64, 64])


In [6]:
# unsqueeze
torch.manual_seed(2025)

ts_01 = torch.rand(size=(4, 5))
print(ts_01)

ts_01_1 = ts_01.unsqueeze(dim=0) # dim 인자가 반드시 사용되어야 함. 
print('ts_01 shape:', ts_01.shape, 'ts_01 unsqueezed shape:', ts_01_1.shape)
print(ts_01_1) #2차원 -> 3차원

tensor([[0.6850, 0.9355, 0.2900, 0.3991, 0.7470],
        [0.0215, 0.0654, 0.7855, 0.3883, 0.6340],
        [0.9447, 0.4773, 0.2861, 0.3887, 0.1099],
        [0.3606, 0.8450, 0.8059, 0.0520, 0.3438]])
ts_01 shape: torch.Size([4, 5]) ts_01 unsqueezed shape: torch.Size([1, 4, 5])
tensor([[[0.6850, 0.9355, 0.2900, 0.3991, 0.7470],
         [0.0215, 0.0654, 0.7855, 0.3883, 0.6340],
         [0.9447, 0.4773, 0.2861, 0.3887, 0.1099],
         [0.3606, 0.8450, 0.8059, 0.0520, 0.3438]]])


In [7]:
# 보통은 3차원 단일 이미지 tensor를 batch 포함 4차원 이미지 tensor로 변환 시 자주 사용
ts_01 = torch.rand(size=(3, 64, 64))
ts_01_1 = ts_01.unsqueeze(dim=0)
print('ts_01 shape:', ts_01.shape, 'ts_01 unsqueezed shape:', ts_01_1.shape)

ts_01 shape: torch.Size([3, 64, 64]) ts_01 unsqueezed shape: torch.Size([1, 3, 64, 64])
